title: endoze
masthead_title: <i class="fa fa-terminal" aria-hidden="true"></i> endoze
email: endoze@endozemedia.com
name: &name Endoze
description: >-
  Random stuff I've learned and decided to share :)
baseurl: ""
url: "https://endoze.github.io"
github_username: *name
repository: "endoze/endoze.github.io"
search: true
og_image: "https://avatars.githubusercontent.com/u/997161?v=4"

links: &links
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/endoze"

author:
  name: *github_username
  avatar: "https://avatars.githubusercontent.com/u/997161?v=4"
  bio: "Software Engineer by day. <br />Hacker by night."
  location: "The Internet"
  links: *links

social:
  type: Person
  name: *name
  links:
    - "https://github.com/endoze"

footer:
  links: *links

minimal_mistakes_skin: "dark"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

exclude:
  - .ruby-version
  -  .git
  - Dockerfile
  - app.ru
  - deploy.yml
  - service.yml
  - .dockerignore
  - docker-compose.yml


include: 
  - site.webmanifest
  - browserconfig.xml
